version: '3'
services:
  nginx-backend-service1:
    image: nginx-backend-service1
    container_name: nginx-backend-service1
    deploy:
      replicas: 1
    ports:
      - 8081:8080
  nginx-backend-service2:
    image: nginx-backend-service2
    container_name: nginx-backend-service2
    deploy:
      replicas: 1
    ports:
      - 8082:8080
  nginx-main:
    image: atomscat-nginx-main
    container_name: atomscat-nginx-main
    depends_on:
      - nginx-backend-service1
      - nginx-backend-service2
    deploy:
      replicas: 1
    ports:
      - 8030:8030